# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Demographics pipeline configuration

schema:
  key: str
  worldpop_population_map: str
  worldpop_population_map_male_age_00_05: str
  worldpop_population_map_male_age_05_09: str
  worldpop_population_map_male_age_10_15: str
  worldpop_population_map_male_age_15_19: str
  worldpop_population_map_male_age_20_25: str
  worldpop_population_map_male_age_25_29: str
  worldpop_population_map_male_age_30_35: str
  worldpop_population_map_male_age_35_39: str
  worldpop_population_map_male_age_40_45: str
  worldpop_population_map_male_age_45_49: str
  worldpop_population_map_male_age_50_55: str
  worldpop_population_map_male_age_55_59: str
  worldpop_population_map_male_age_60_65: str
  worldpop_population_map_male_age_65_69: str
  worldpop_population_map_male_age_70_75: str
  worldpop_population_map_male_age_75_79: str
  worldpop_population_map_male_age_80_99: str
  worldpop_population_map_female_age_00_05: str
  worldpop_population_map_female_age_05_09: str
  worldpop_population_map_female_age_10_15: str
  worldpop_population_map_female_age_15_19: str
  worldpop_population_map_female_age_20_25: str
  worldpop_population_map_female_age_25_29: str
  worldpop_population_map_female_age_30_35: str
  worldpop_population_map_female_age_35_39: str
  worldpop_population_map_female_age_40_45: str
  worldpop_population_map_female_age_45_49: str
  worldpop_population_map_female_age_50_55: str
  worldpop_population_map_female_age_55_59: str
  worldpop_population_map_female_age_60_65: str
  worldpop_population_map_female_age_65_69: str
  worldpop_population_map_female_age_70_75: str
  worldpop_population_map_female_age_75_79: str
  worldpop_population_map_female_age_80_99: str

auxiliary:
  metadata: ./src/data/metadata.csv
  country_codes: ./src/data/country_codes.csv

sources:

  - name: pipelines.worldpop.worldpop.WorldPopPopulationDataSource
