# This is a basic workflow to help you get started with Actions

name: CI

# Run only after a successful push to master
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    
    - name: Generate outputs from time series
      run: python scripts/aggregate.py
    
    - uses: EndBug/add-and-commit@v4
      with:
        add: 'output'
        author_name: Github Bot
        message: 'Auto update'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
